export const SET_SELECTION_MENU = 'HEADER/SET_SELECTION_MENU';
export const SET_NEW_GAME = 'FINISH/SET_NEW_GAME';
export const SET_RANDOM_NUMBER = 'SET_RANDOM_NUMBER';
export const SET_GUESS_ITEM = 'SET_GUESS_ITEM';
export const CLICK_ON_BIRDS = 'CLICK_ON_BIRDS';
export const PICK_BIRD = 'SET_CLICK_ITEM';
export const SET_ACCUM_SCORE = 'SET_ACCUM_SCORE';
export const SET_TOTAL_SCORE = 'SET_TOTAL_SCORE';